=== anthonybyateo/05_JavaST_2019/task4/data/tariffs.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.training.by"
        xmlns:tns="http://www.training.by"
        elementFormDefault="qualified">

    <element name="tariffs">
        <complexType>
            <sequence>
                <element ref="tns:tariff"
                         minOccurs="1"
                         maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>

    <element name="tariff" type="tns:TariffType" abstract="true"></element>
    <element name="smartphone" type="tns:Smartphone" substitutionGroup="tns:tariff"></element>
    <element name="internet" type="tns:Internet" substitutionGroup="tns:tariff"></element>
    <element name="only_calls" type="tns:Only_calls" substitutionGroup="tns:tariff"></element>

    <complexType name="TariffType">
        <sequence>
            <element name="name" type="string" />
            <element name="operator_name" type="string" />
            <element name="payroll" type="tns:nonNegativedecimal" />
            <element name="date" type="tns:Date" />
        </sequence>

        <attribute name="login" type="tns:Login" use="required" />
    </complexType>

    <complexType name="Smartphone">
        <complexContent>
            <extension base="tns:TariffType">
                <sequence>
                    <element name="call_prices" type="tns:Call_prices" />
                    <element name="free_minute" type="nonNegativeInteger" />
                    <element name="internet_price" type="tns:nonNegativedecimal" />
                    <element name="free_mgb" type="tns:nonNegativedecimal" />
                    <element name="parameters" type="tns:Parameters" />
                </sequence>

                <attribute name="tarrifing" type="tns:Tarrifing" use="optional" default="oneminute" />
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Internet">
        <complexContent>
            <extension base="tns:TariffType">
                <sequence>
                    <element name="internet_price" type="tns:nonNegativedecimal" />
                    <element name="free_mgb" type="tns:nonNegativedecimal" />
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Only_calls">
        <complexContent>
            <extension base="tns:TariffType">
                <sequence>
                    <element name="call_prices" type="tns:Call_prices" />
                    <element name="free_minute" type="nonNegativeInteger" />
                    <element name="parameters" type="tns:Parameters" />
                </sequence>

                <attribute name="tarrifing" type="tns:Tarrifing" use="optional" default="oneminute" />
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="nonNegativedecimal">
        <restriction base="decimal">
            <minInclusive value="0"/>
        </restriction>
    </simpleType>

    <complexType name="Call_prices">
        <sequence>
            <element name="inside" type="tns:nonNegativedecimal" />
            <element name="outside" type="tns:nonNegativedecimal" />
            <element name="landline" type="tns:nonNegativedecimal" />
            <element name="sms" type="tns:nonNegativedecimal" />
        </sequence>
    </complexType>

    <complexType name="Parameters">
        <sequence>
            <element name="favorite_number" type="nonNegativeInteger" />
            <element name="connection_fee" type="tns:nonNegativedecimal" />
        </sequence>
    </complexType>

    <complexType name="Date">
        <sequence>
            <element name="start" type="date" />
            <element name="finish" type="date" />
        </sequence>
    </complexType>

    <simpleType name="Login">
        <restriction base="ID">
            <pattern value="[a-zA-Z0-9]{3,20}"/>
        </restriction>
    </simpleType>

    <simpleType name="Tarrifing">
        <restriction base="string">
            <enumeration value="oneminute"></enumeration>
            <enumeration value="12seconds"></enumeration>
        </restriction>
    </simpleType>

</schema>

=== anthonybyateo/05_JavaST_2019/task4/data/tariffs.xml
<?xml version="1.0" encoding="UTF-8"?>
<tariffs xmlns="http://www.training.by/tariffs"
         xmlns:tns="http://www.w3.org/2001/XMLSchema-instance"
         tns:schemaLocation="http://www.training.by/tariffs tariffs.xsd">

    <smartphone idnumber="super" tariffing="oneminute">
        <name>Супер</name>
        <operator_name>МТС</operator_name>
        <payroll>10.5</payroll>
        <date>
            <start>2019-03-22</start>
            <finish>2019-06-22</finish>
        </date>
        <call_prices>
            <inside>0.009</inside>
            <outside>0.021</outside>
            <landline>0.031</landline>
            <sms>0.002</sms>
        </call_prices>
        <free_minute>100</free_minute>
        <internet_price>0.01</internet_price>
        <free_mgb>100</free_mgb>
        <parameters>
            <favorite_number>2</favorite_number>
            <connection_fee>2.97</connection_fee>
        </parameters>
    </smartphone>

    <smartphone idnumber="super2" tariffing="oneminute">
        <name>Супер 2</name>
        <operator_name>МТС</operator_name>
        <payroll>15.5</payroll>
        <date>
            <start>2019-03-12</start>
            <finish>2019-08-12</finish>
        </date>
        <call_prices>
            <inside>0.006</inside>
            <outside>0.011</outside>
            <landline>0.011</landline>
            <sms>0.001</sms>
        </call_prices>
        <free_minute>200</free_minute>
        <internet_price>0.01</internet_price>
        <free_mgb>200</free_mgb>
        <parameters>
            <favorite_number>2</favorite_number>
            <connection_fee>2.97</connection_fee>
        </parameters>
    </smartphone>

    <smartphone idnumber="super4" tariffing="oneminute">
        <name>Супер 4</name>
        <operator_name>МТС</operator_name>
        <payroll>20.5</payroll>
        <date>
            <start>2019-03-12</start>
            <finish>2019-09-12</finish>
        </date>
        <call_prices>
            <inside>0.006</inside>
            <outside>0.011</outside>
            <landline>0.011</landline>
            <sms>0.001</sms>
        </call_prices>
        <free_minute>400</free_minute>
        <internet_price>0.01</internet_price>
        <free_mgb>400</free_mgb>
        <parameters>
            <favorite_number>2</favorite_number>
            <connection_fee>2.97</connection_fee>
        </parameters>
    </smartphone>

    <smartphone idnumber="super8" tariffing="oneminute">
        <name>Супер 8</name>
        <operator_name>МТС</operator_name>
        <payroll>25.5</payroll>
        <date>
            <start>2019-03-12</start>
            <finish>2019-12-12</finish>
        </date>
        <call_prices>
            <inside>0.006</inside>
            <outside>0.011</outside>
            <landline>0.011</landline>
            <sms>0.001</sms>
        </call_prices>
        <free_minute>800</free_minute>
        <internet_price>0.01</internet_price>
        <free_mgb>800</free_mgb>
        <parameters>
            <favorite_number>8</favorite_number>
            <connection_fee>2.97</connection_fee>
        </parameters>
    </smartphone>

    <smartphone idnumber="superMax" tariffing="oneminute">
        <name>Супер Max</name>
        <operator_name>МТС</operator_name>
        <payroll>30.5</payroll>
        <date>
            <start>2019-03-12</start>
            <finish>2019-09-12</finish>
        </date>
        <call_prices>
            <inside>0.006</inside>
            <outside>0.011</outside>
            <landline>0.011</landline>
            <sms>0.001</sms>
        </call_prices>
        <free_minute>1000</free_minute>
        <internet_price>0.01</internet_price>
        <free_mgb>1000</free_mgb>
        <parameters>
            <favorite_number>10</favorite_number>
            <connection_fee>2.97</connection_fee>
        </parameters>
    </smartphone>


    <internet idnumber="bit">
        <name>Бит</name>
        <operator_name>МТС</operator_name>
        <payroll>15.5</payroll>
        <date>
            <start>2019-04-25</start>
            <finish>2019-07-25</finish>
        </date>
        <internet_price>0.01</internet_price>
        <free_mgb>200</free_mgb>
    </internet>

    <internet idnumber="bit2">
        <name>Бит 2</name>
        <operator_name>МТС</operator_name>
        <payroll>17.5</payroll>
        <date>
            <start>2019-04-25</start>
            <finish>2019-07-25</finish>
        </date>
        <internet_price>0.01</internet_price>
        <free_mgb>400</free_mgb>
    </internet>

    <internet idnumber="bit4">
        <name>Бит 4</name>
        <operator_name>МТС</operator_name>
        <payroll>20.5</payroll>
        <date>
            <start>2019-04-25</start>
            <finish>2019-07-25</finish>
        </date>
        <internet_price>0.01</internet_price>
        <free_mgb>600</free_mgb>
    </internet>

    <internet idnumber="bitMax">
        <name>Бит Max</name>
        <operator_name>МТС</operator_name>
        <payroll>25.5</payroll>
        <date>
            <start>2019-04-25</start>
            <finish>2019-12-25</finish>
        </date>
        <internet_price>0.01</internet_price>
        <free_mgb>1000</free_mgb>
    </internet>

    <only_calls idnumber="easySay" tariffing="oneminute">
        <name>Легко сказать</name>
        <operator_name>МТС</operator_name>
        <payroll>15.5</payroll>
        <date>
            <start>2019-04-25</start>
            <finish>2019-07-25</finish>
        </date>
        <call_prices>
            <inside>0.009</inside>
            <outside>0.021</outside>
            <landline>0.031</landline>
            <sms>0.002</sms>
        </call_prices>
        <free_minute>150</free_minute>
        <parameters>
            <favorite_number>2</favorite_number>
            <connection_fee>2.97</connection_fee>
        </parameters>
    </only_calls>

    <only_calls idnumber="easySay2" tariffing="oneminute">
        <name>Легко сказать 2</name>
        <operator_name>Velcome</operator_name>
        <payroll>15.5</payroll>
        <date>
            <start>2019-04-25</start>
            <finish>2019-07-25</finish>
        </date>
        <call_prices>
            <inside>0.005</inside>
            <outside>0.011</outside>
            <landline>0.011</landline>
            <sms>0.001</sms>
        </call_prices>
        <free_minute>250</free_minute>
        <parameters>
            <favorite_number>2</favorite_number>
            <connection_fee>2.97</connection_fee>
        </parameters>
    </only_calls>

    <only_calls idnumber="easySays4" tariffing="oneminute">
        <name>Легко сказать 4</name>
        <operator_name>МТС</operator_name>
        <payroll>25.5</payroll>
        <date>
            <start>2019-04-25</start>
            <finish>2019-07-25</finish>
        </date>
        <call_prices>
            <inside>0.001</inside>
            <outside>0.001</outside>
            <landline>0.001</landline>
            <sms>0.0002</sms>
        </call_prices>
        <free_minute>550</free_minute>
        <parameters>
            <favorite_number>2</favorite_number>
            <connection_fee>2.97</connection_fee>
        </parameters>
    </only_calls>

    <only_calls idnumber="easySaysMax" tariffing="oneminute">
        <name>Легко сказать Max</name>
        <operator_name>Velcome</operator_name>
        <payroll>35.5</payroll>
        <date>
            <start>2019-04-25</start>
            <finish>2019-11-25</finish>
        </date>
        <call_prices>
            <inside>0.001</inside>
            <outside>0.001</outside>
            <landline>0.001</landline>
            <sms>0.0002</sms>
        </call_prices>
        <free_minute>1000</free_minute>
        <parameters>
            <favorite_number>4</favorite_number>
            <connection_fee>2.97</connection_fee>
        </parameters>
    </only_calls>

    <smartphone idnumber="Comfort" tariffing="oneminute">
        <name>Комфорт</name>
        <operator_name>Velcome</operator_name>
        <payroll>10.5</payroll>
        <date>
            <start>2019-03-22</start>
            <finish>2019-07-22</finish>
        </date>
        <call_prices>
            <inside>0.006</inside>
            <outside>0.031</outside>
            <landline>0.041</landline>
            <sms>0.001</sms>
        </call_prices>
        <free_minute>500</free_minute>
        <internet_price>0.03</internet_price>
        <free_mgb>500</free_mgb>
        <parameters>
            <favorite_number>0</favorite_number>
            <connection_fee>2.97</connection_fee>
        </parameters>
    </smartphone>

    <smartphone idnumber="Comfort2" tariffing="oneminute">
        <name>Комфорт 2</name>
        <operator_name>Velcome</operator_name>
        <payroll>15.5</payroll>
        <date>
            <start>2019-03-22</start>
            <finish>2019-08-22</finish>
        </date>
        <call_prices>
            <inside>0.006</inside>
            <outside>0.031</outside>
            <landline>0.041</landline>
            <sms>0.001</sms>
        </call_prices>
        <free_minute>800</free_minute>
        <internet_price>0.03</internet_price>
        <free_mgb>800</free_mgb>
        <parameters>
            <favorite_number>0</favorite_number>
            <connection_fee>2.97</connection_fee>
        </parameters>
    </smartphone>

    <smartphone idnumber="Comfort4" tariffing="oneminute">
        <name>Комфорт 4</name>
        <operator_name>Velcome</operator_name>
        <payroll>20.5</payroll>
        <date>
            <start>2019-03-22</start>
            <finish>2019-09-22</finish>
        </date>
        <call_prices>
            <inside>0.006</inside>
            <outside>0.021</outside>
            <landline>0.021</landline>
            <sms>0.001</sms>
        </call_prices>
        <free_minute>900</free_minute>
        <internet_price>0.01</internet_price>
        <free_mgb>800</free_mgb>
